name: 'Add Secure Code Warrior contextual training to SARIF'
description: 'Add contextual application security training to SARIF files, providing links to secure coding exercises and explainer videos'
author: 'SecureCodeWarrior'
branding:
  icon: 'shield'  
  color: 'orange'
inputs:
  inputSarifFile:
    description: 'Relative location of SARIF file(s) to process'
    required: true
    default: './findings.sarif'
  outputSarifFile:
    description: 'Relative destination location for processed SARIF file(s)'
    required: true
    default: './findings.processed.sarif'
  githubToken:
    description: 'Provide `secrets.GITHUB_TOKEN` to use the GitHub access token automatically supplied by GitHub Workflows'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
